import { StyleSheet } from "@/stitches/StyleSheet";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

interface Props {
  children: React.ReactNode;
}

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <head>
        <meta name="color-scheme" content="dark" />
        <StyleSheet />
      </head>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
