name: 'Build And Push Event Demo'

on:
  push:
    paths:
      - '.github/workflows/event-demo.yaml'
      - 'event-demo/**'

jobs:
  docker:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Docker login
        run: echo ${{ secrets.PAT }} | docker login ghcr.io --username yomanz --password-stdin

      - name: Docker build
        run: docker build -t ghcr.io/widgetbot-io/demos:event-demo event-demo

      - name: Docker push tag latest
        run: docker push ghcr.io/widgetbot-io/embed:event-demo
